<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Magewirephp\MagewireBackendGrid\Grid\DataProvider\GridDataProviderInterface;
use Magewirephp\MagewireBackendGrid\Magewire\Grid;
use Magewirephp\MagewireBackendGrid\ViewModel\BlockRenderer;

/** @var Template $block */
/** @var BlockRenderer $renderer */
$renderer = $block->getBlockRenderer();
$renderer->setBlock($block);

/** @var Grid $magewire */
/** @var GridDataProviderInterface $gridDataProvider */
$gridDataProvider = $block->getGridDataProvider();
$magewire->setGridDataProvider($gridDataProvider);
?>

<div class="grid">
    <?= $renderer->getChildHtml('actions') ?>
    <div class="page-columns">
        <div class="main-col">
            <div class="admin__data-grid-outer-wrap">
                <?= $renderer->getChildHtml('spinner') ?>

                <div class="admin__data-grid-header">
                    <div class="admin__data-grid-header-row">
                        <?= $renderer->getChildHtml('search') ?>
                        <?= $renderer->getChildHtml('pagination') ?>
                        <?= $renderer->getChildHtml('grid-actions') ?>
                        <?= $renderer->getChildHtml('filters-actions') ?>
                        <div class="admin__control-support-text">
                            <?= $magewire->totalItems ?> <?= __('records found') ?>
                        </div>
                    </div>
                </div>

                <!--
                <div class="admin__data-grid-header-row row row-gutter">
                    <div class="col-xs-2">
                        <div class="action-select-wrap">
                        </div>
                    </div>
                </div>
                -->

                <div class="admin__data-grid-wrap" data-role="grid-wrapper">
                    <table class="data-grid" data-role="grid">
                        <thead>
                        <tr>
                            <?php foreach ($gridDataProvider->getColumns() as $code => $label): ?>
                                <th class="data-grid-th">
                                    <span class="data-grid-cell-content"><?= __($label) ?></span>
                                </th>
                            <?php endforeach; ?>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach($gridDataProvider->getItems() as $item): ?>
                        <tr class="data-row">
                            <?php foreach ($gridDataProvider->getColumns() as $code => $label): ?>
                            <td class="data-grid-cell">
                                <div class="data-grid-cell-content">
                                    <?= $item->getData($code) ?>
                                </div>
                            </td>
                            <?php endforeach; ?>
                        </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>


            </div>
        </div>
    </div>
</div>
