<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>

<div class="grid">
    <?= $block->getChildHtml('actions') ?>
    <div class="page-columns">
        <div class="main-col">
            <div class="admin__data-grid-outer-wrap">
                <?= $block->getChildHtml('spinner') ?>

                <div class="admin__data-grid-header">
                    <div class="admin__data-grid-header-row">
                        <?= $block->getChildHtml('search') ?>
                        <?= $block->getChildHtml('pagination') ?>
                        <?= $block->getChildHtml('grid-actions') ?>
                        <?= $block->getChildHtml('filters-actions') ?>
                        <?= $block->getChildHtml('records') ?>
                    </div>
                </div>

                <!--
                <div class="admin__data-grid-header-row row row-gutter">
                    <div class="col-xs-2">
                        <div class="action-select-wrap">
                        </div>
                    </div>
                </div>
                -->
                
                <?= $block->getChildHtml('data') ?>
            </div>
        </div>
    </div>
</div>
