<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Magewirephp\MagewireBackendGrid\Grid\DataProvider\GridDataProviderInterface;
use Magewirephp\MagewireBackendGrid\Magewire\Grid;

/** @var Template $block */
/** @var Grid $magewire */
/** @var GridDataProviderInterface $gridDataProvider */
$gridDataProvider = $magewire->getGridDataProvider();
?>
<div class="admin__data-grid-wrap" data-role="grid-wrapper">
    <button wire:click="$refresh()">Refresh</button>

    <table class="data-grid" data-role="grid">
        <thead>
        <tr>
            <?php
            foreach ($magewire->getColumns() as $code => $label): ?>
                <th class="data-grid-th">
                    <span class="data-grid-cell-content"><?= __($label) ?></span>
                </th>
            <?php
            endforeach; ?>
        </tr>
        </thead>
        <tbody>
        <?php
        foreach ($magewire->getItems() as $item): ?>
            <tr class="data-row">
                <?php
                foreach ($magewire->getColumns() as $code => $label): ?>
                    <td class="data-grid-cell">
                        <div class="data-grid-cell-content">
                            <?= $item->getData($code) ?>
                        </div>
                    </td>
                <?php
                endforeach; ?>
            </tr>
        <?php
        endforeach; ?>
        </tbody>
    </table>
</div>
