<?php
declare(strict_types=1);

/** @var Grid $magewire */

use Magewirephp\MagewireBackendGrid\Magewire\Grid;

$limits = [20, 30, 50, 100, 200];
?>
<div class="admin__data-grid-pager-wrap">
    <div class="selectmenu">
        <div class="selectmenu-value">
            <input type="text" aria-labelledby="per-page-text" id="product_listing.product_listing.listing_top.listing_paging_sizes">
        </div>
        <button class="selectmenu-toggle" type="button" aria-labelledby="per-page-text select-button-text">
            <span id="select-button-text"><?= __('Select') ?></span>
        </button>
        <div class="selectmenu-items">
            <ul>
                <?php foreach($limits as $limit): ?>
                <li>
                    <div class="selectmenu-item">
                        <button class="selectmenu-item-action" type="button"><?= $limit ?></button>
                    </div>
                </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
    <label class="admin__control-support-text" id="per-page-text" for="product_listing.product_listing.listing_top.listing_paging_sizes"><?= __('per page') ?></label>

    <div class="admin__data-grid-pager">
        <button wire:click="decrementPage" class="action-previous" type="button" title="<?= __('Previous Page') ?>" <?= ($magewire->page < 2) ? 'disabled' : '' ?>></button>

        <input wire:model="page" class="admin__control-text" type="number" id="current_page" value="<?= $magewire->page ?>"/>
        <label class="admin__control-support-text" for="current_page">of <?= $magewire->totalPages ?> pages</label>

        <button wire:click="incrementPage" class="action-next" type="button" title="<?= __('Next Page') ?>" <?= ($magewire->page >= $magewire->totalPages) ? 'disabled' : '' ?>></button>
    </div>
</div>
